name: npm publish
on:
  release:
    types: [published]

jobs:
  publish-npm:
    name: Build and Publish to npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          cache: "npm"
          registry-url: "https://registry.npmjs.org"
      - run: npm ci --ignore-optional
      - run: npm run build
      - run: npm run release
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
